version: "3.8"

services:
  backend:
    image: dynprobangalore/dynviz-v1:backend
    container_name: dynviz-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: dynprobangalore/dynviz-v1:frontend
    container_name: dynviz-frontend
    ports:
      - "3000:3000"
    restart: always
